# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sekia < Formula
  desc "Multi-agent event bus - daemon and CLI"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia_0.2.2_darwin_amd64.tar.gz"
      sha256 "3ae1ba4cd0c919e086f7ada54e0bd5a7d866f1fb42b498a036b2aafe0860734c"

      define_method(:install) do
        bin.install "sekiad"
        bin.install "sekiactl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia_0.2.2_darwin_arm64.tar.gz"
      sha256 "41998742d8f00c257d91df5cea28cc39fc02265d15deb860806517ddf123e425"

      define_method(:install) do
        bin.install "sekiad"
        bin.install "sekiactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia_0.2.2_linux_amd64.tar.gz"
      sha256 "ede4b618cb264867dbfafd73589561379d5db36fe3ee7b83c8b80abbb3f4bfc8"
      define_method(:install) do
        bin.install "sekiad"
        bin.install "sekiactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia_0.2.2_linux_arm64.tar.gz"
      sha256 "c0028bfcaabd0810e6088cc905266d8a26a100adaa61d5dc33f06c4ef3648c82"
      define_method(:install) do
        bin.install "sekiad"
        bin.install "sekiactl"
      end
    end
  end

  service do
    run [opt_bin/"sekiad"]
    keep_alive true
    log_path var/"log/sekiad.log"
    error_log_path var/"log/sekiad.log"
  end

  test do
    system bin/"sekiad", "--help"
    system bin/"sekiactl", "--help"
  end
end
