# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaGithub < Formula
  desc "sekia GitHub agent - webhook and polling bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.1.5"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-github_0.1.5_darwin_amd64.tar.gz"
      sha256 "f1e1f761fd95958462624ed42dd05442f40344d72ecd7f5edf313934188c3782"

      define_method(:install) do
        bin.install "sekia-github"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-github_0.1.5_darwin_arm64.tar.gz"
      sha256 "73d257104baacdd605be5975a3256566a04e57559d97f02ea41923d63e241d4d"

      define_method(:install) do
        bin.install "sekia-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-github_0.1.5_linux_amd64.tar.gz"
      sha256 "49fc802de64201379f263370951f720fa847d423139cc5901249295d2e44512b"
      define_method(:install) do
        bin.install "sekia-github"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-github_0.1.5_linux_arm64.tar.gz"
      sha256 "99a954b03bd0d147e52bce3d420febb5d4e3581c822d6df0977184ea2d5ce893"
      define_method(:install) do
        bin.install "sekia-github"
      end
    end
  end

  service do
    run [opt_bin/"sekia-github"]
    keep_alive true
    log_path var/"log/sekia-github.log"
    error_log_path var/"log/sekia-github.log"
  end

  test do
    system bin/"sekia-github", "--help"
  end
end
