# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaGithub < Formula
  desc "sekia GitHub agent - webhook and polling bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.2.0"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia-github_0.2.0_darwin_amd64.tar.gz"
      sha256 "e22fe6db9abf1622bfea0cea7ce3ac07a556cf267815eebcf79d37b0eac97259"

      define_method(:install) do
        bin.install "sekia-github"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia-github_0.2.0_darwin_arm64.tar.gz"
      sha256 "d98723ea558461269074dafe6f5c9153abecf2af7e7a77a7a09883938f1aa855"

      define_method(:install) do
        bin.install "sekia-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia-github_0.2.0_linux_amd64.tar.gz"
      sha256 "6b829df2ea12681a8f92c925a15bb3ca79dea62f5e7a76f2b7e7fcdeca1f74b2"
      define_method(:install) do
        bin.install "sekia-github"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia-github_0.2.0_linux_arm64.tar.gz"
      sha256 "45ac8cb2321d5eebd510b07efd55551886eeeff03f821a870999a412898eaded"
      define_method(:install) do
        bin.install "sekia-github"
      end
    end
  end

  service do
    run [opt_bin/"sekia-github"]
    keep_alive true
    log_path var/"log/sekia-github.log"
    error_log_path var/"log/sekia-github.log"
  end

  test do
    system bin/"sekia-github", "--help"
  end
end
