# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaLinear < Formula
  desc "sekia Linear agent - GraphQL polling bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.1.5"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-linear_0.1.5_darwin_amd64.tar.gz"
      sha256 "81c0133bea7b8d1418de55eb74ae7ad27a2a9865b57a7785a78ad5801eccd7c9"

      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-linear_0.1.5_darwin_arm64.tar.gz"
      sha256 "1767a0d9a920add4038e01fd41b7c60322d70bd6f25c6a7e961817f85596a395"

      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-linear_0.1.5_linux_amd64.tar.gz"
      sha256 "706b41bcc6f78ffc80f7617aaf6f4533680c43171f8bffcc795937c6644c4a46"
      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-linear_0.1.5_linux_arm64.tar.gz"
      sha256 "7a4d4aa523356471996141fc6639ac14a149ca2144a8da9a6dc135916fb15845"
      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
  end

  service do
    run [opt_bin/"sekia-linear"]
    keep_alive true
    log_path var/"log/sekia-linear.log"
    error_log_path var/"log/sekia-linear.log"
  end

  test do
    system bin/"sekia-linear", "--help"
  end
end
