# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaSlack < Formula
  desc "sekia Slack agent - Socket Mode bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.2.3"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.3/sekia-slack_0.2.3_darwin_amd64.tar.gz"
      sha256 "03e0a41615290de26b87bbef645a76fcfdf28bec728f1dcbf9b9acf4d2b922b1"

      define_method(:install) do
        bin.install "sekia-slack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.3/sekia-slack_0.2.3_darwin_arm64.tar.gz"
      sha256 "3ccd2d4da796937e8eaddb0b48e2c38e49ddf9c79e8acbfc0ebb9102811951a5"

      define_method(:install) do
        bin.install "sekia-slack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.3/sekia-slack_0.2.3_linux_amd64.tar.gz"
      sha256 "b3ff2513dc7ac2d48e5cd44755038eb094eed01c8edcce45304368fab68e037f"
      define_method(:install) do
        bin.install "sekia-slack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.3/sekia-slack_0.2.3_linux_arm64.tar.gz"
      sha256 "7c7d122d6a8975f20a3d5cfedb19ce01c7c36c8adcb22593844a1060da6c9360"
      define_method(:install) do
        bin.install "sekia-slack"
      end
    end
  end

  service do
    run [opt_bin/"sekia-slack"]
    keep_alive true
    log_path var/"log/sekia-slack.log"
    error_log_path var/"log/sekia-slack.log"
  end

  test do
    system bin/"sekia-slack", "--help"
  end
end
