# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaGoogle < Formula
  desc "sekia Google agent - Gmail and Calendar bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.1.6"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.6/sekia-google_0.1.6_darwin_amd64.tar.gz"
      sha256 "a0a9e5a752ae65bc9c82caad2ae22d2d4513b9bdf206955e0fec24ec6bfd4a19"

      define_method(:install) do
        bin.install "sekia-google"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.6/sekia-google_0.1.6_darwin_arm64.tar.gz"
      sha256 "b644da3051f33d4f55056c46b0a6ef7cc89731c29e94e6c4cd5fb1676c3103c6"

      define_method(:install) do
        bin.install "sekia-google"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.6/sekia-google_0.1.6_linux_amd64.tar.gz"
      sha256 "c6076994bfa1f1c4f8a130d346ef0e573dcf78b55e2e9d4d9cae95d9a230e18a"
      define_method(:install) do
        bin.install "sekia-google"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.6/sekia-google_0.1.6_linux_arm64.tar.gz"
      sha256 "eb16d9b1fd419da18bfd0adb002f04030007a2079e08178fda526b453a0f4e84"
      define_method(:install) do
        bin.install "sekia-google"
      end
    end
  end

  service do
    run [opt_bin/"sekia-google"]
    keep_alive true
    log_path var/"log/sekia-google.log"
    error_log_path var/"log/sekia-google.log"
  end

  test do
    system bin/"sekia-google", "--help"
  end
end
