# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaMcp < Formula
  desc "sekia MCP server - Model Context Protocol adapter"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.2.2"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia-mcp_0.2.2_darwin_amd64.tar.gz"
      sha256 "426937337e9ce6f736b8ad57f3fe6a3161878351effb077bad343e22584ef5e0"

      define_method(:install) do
        bin.install "sekia-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia-mcp_0.2.2_darwin_arm64.tar.gz"
      sha256 "c7b49887f2a4d37f155e36eb6b580d08dbccd48fe9ff2c0119b72cf5897b8af3"

      define_method(:install) do
        bin.install "sekia-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia-mcp_0.2.2_linux_amd64.tar.gz"
      sha256 "b7491a37642fa2995b189334adeee78180e2505d9e89b1ca8a54407ca48a247e"
      define_method(:install) do
        bin.install "sekia-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia-mcp_0.2.2_linux_arm64.tar.gz"
      sha256 "eca51c0624a398b21829546873e470a43af5bb71ad69472203b82d2f19cd03ba"
      define_method(:install) do
        bin.install "sekia-mcp"
      end
    end
  end

  test do
    system bin/"sekia-mcp", "--help"
  end
end
