# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sekia < Formula
  desc "Multi-agent event bus for workflow automation"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.0.16"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.0.16/sekia_0.0.16_darwin_amd64.tar.gz"
      sha256 "ecfc9916a70cf9401459c4b346c9621a4cf82661a33bfa247d30534e82d473c2"

      def install
        bin.install "sekiad"
        bin.install "sekiactl"
        bin.install "sekia-github"
        bin.install "sekia-slack"
        bin.install "sekia-linear"
        bin.install "sekia-google"
        bin.install "sekia-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.0.16/sekia_0.0.16_darwin_arm64.tar.gz"
      sha256 "fdd18c07999dbbf2aeed1730064cb6da095641c642ba30d3d52443da309f83b8"

      def install
        bin.install "sekiad"
        bin.install "sekiactl"
        bin.install "sekia-github"
        bin.install "sekia-slack"
        bin.install "sekia-linear"
        bin.install "sekia-google"
        bin.install "sekia-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.0.16/sekia_0.0.16_linux_amd64.tar.gz"
      sha256 "e5d26904a40c91566f0e29be7ae4fd02ca2037179d2e1ba2dae2238b0779d250"
      def install
        bin.install "sekiad"
        bin.install "sekiactl"
        bin.install "sekia-github"
        bin.install "sekia-slack"
        bin.install "sekia-linear"
        bin.install "sekia-google"
        bin.install "sekia-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.0.16/sekia_0.0.16_linux_arm64.tar.gz"
      sha256 "539746985009cd71a5145f224eb4405521bfd6343bcfff38a517c233afb84e71"
      def install
        bin.install "sekiad"
        bin.install "sekiactl"
        bin.install "sekia-github"
        bin.install "sekia-slack"
        bin.install "sekia-linear"
        bin.install "sekia-google"
        bin.install "sekia-mcp"
      end
    end
  end

  test do
    system bin/"sekiad", "--help"
    system bin/"sekiactl", "--help"
  end
end
