# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaMcp < Formula
  desc "sekia MCP server - Model Context Protocol adapter"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.1.4"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.4/sekia-mcp_0.1.4_darwin_amd64.tar.gz"
      sha256 "fa9d65175781e724e33a8f73945700065e0fd94a8563c3a9a2ef7e2b242ad1f2"

      define_method(:install) do
        bin.install "sekia-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.4/sekia-mcp_0.1.4_darwin_arm64.tar.gz"
      sha256 "5152f96f8304db684437be4fb3a1b08b3bea156c7215cb7a5f16777ede688c31"

      define_method(:install) do
        bin.install "sekia-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.4/sekia-mcp_0.1.4_linux_amd64.tar.gz"
      sha256 "4c3a3398e167ae6f79d2faa12acf48fd8b18f220a5737161686097786811d4ac"
      define_method(:install) do
        bin.install "sekia-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.4/sekia-mcp_0.1.4_linux_arm64.tar.gz"
      sha256 "b6ea934d7acaa548d966f80ea9456dc254e4f6e879565d7942ea33b3e63c56a9"
      define_method(:install) do
        bin.install "sekia-mcp"
      end
    end
  end

  test do
    system bin/"sekia-mcp", "--help"
  end
end
