# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaGoogle < Formula
  desc "sekia Google agent - Gmail and Calendar bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.1.5"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-google_0.1.5_darwin_amd64.tar.gz"
      sha256 "39a0416bf6c2118b374e1c1ee422e64ace4dff4c8d5ff9ba15ffd6cedb879840"

      define_method(:install) do
        bin.install "sekia-google"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-google_0.1.5_darwin_arm64.tar.gz"
      sha256 "871fe3e7300dd4e5a367616bd37d5fe933a01161225c755b4a9e8c222748850c"

      define_method(:install) do
        bin.install "sekia-google"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-google_0.1.5_linux_amd64.tar.gz"
      sha256 "2cff2cc6034b0e6e9435902d31c71c34b667c5866a0f629feaaf41929ca43e21"
      define_method(:install) do
        bin.install "sekia-google"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.5/sekia-google_0.1.5_linux_arm64.tar.gz"
      sha256 "efb0ce48407ca2858dc917be7160c2d41ad9db6d6183e79c11e8c9e97e0db024"
      define_method(:install) do
        bin.install "sekia-google"
      end
    end
  end

  service do
    run [opt_bin/"sekia-google"]
    keep_alive true
    log_path var/"log/sekia-google.log"
    error_log_path var/"log/sekia-google.log"
  end

  test do
    system bin/"sekia-google", "--help"
  end
end
