# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaGithub < Formula
  desc "sekia GitHub agent - webhook and polling bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.2.2"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia-github_0.2.2_darwin_amd64.tar.gz"
      sha256 "0a569792ecbecb3b03cad10387e8943ea5a84b45e79ddbfbf2548fef3ca7ae43"

      define_method(:install) do
        bin.install "sekia-github"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia-github_0.2.2_darwin_arm64.tar.gz"
      sha256 "b18ad73de5d3b2bdc071239f4375661aa295c434b9cbc69a67f4bafdbb2f0d26"

      define_method(:install) do
        bin.install "sekia-github"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia-github_0.2.2_linux_amd64.tar.gz"
      sha256 "9f4b466353dbc16cda867ab04712d0c428f2ce88d1fd0e2c17509f47820aafcb"
      define_method(:install) do
        bin.install "sekia-github"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.2/sekia-github_0.2.2_linux_arm64.tar.gz"
      sha256 "73954848900d09f5a1461e89191de51e0daa11ba5429a6ed9434cca8b87594cd"
      define_method(:install) do
        bin.install "sekia-github"
      end
    end
  end

  service do
    run [opt_bin/"sekia-github"]
    keep_alive true
    log_path var/"log/sekia-github.log"
    error_log_path var/"log/sekia-github.log"
  end

  test do
    system bin/"sekia-github", "--help"
  end
end
