# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaLinear < Formula
  desc "sekia Linear agent - GraphQL polling bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.1.6"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.6/sekia-linear_0.1.6_darwin_amd64.tar.gz"
      sha256 "86b72cf2157b25b3df5e73a323a24cf7fd746b779139f67029157f5afed48e35"

      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.6/sekia-linear_0.1.6_darwin_arm64.tar.gz"
      sha256 "174c2155cb21c46f07d17b6d91ed4790edd9f93121796d9681958872c7864c1f"

      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.6/sekia-linear_0.1.6_linux_amd64.tar.gz"
      sha256 "9e71f191db34a5a588b44f8308fcc566dd8b87ab82474828c1355ace0fbdb40f"
      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.6/sekia-linear_0.1.6_linux_arm64.tar.gz"
      sha256 "45cc9887c020c01b839c9b596d4975a05f2952babee36069238ccd1d5b4a35e3"
      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
  end

  service do
    run [opt_bin/"sekia-linear"]
    keep_alive true
    log_path var/"log/sekia-linear.log"
    error_log_path var/"log/sekia-linear.log"
  end

  test do
    system bin/"sekia-linear", "--help"
  end
end
