# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sekia < Formula
  desc "Multi-agent event bus - daemon and CLI"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia_0.2.0_darwin_amd64.tar.gz"
      sha256 "51e82e824e67eececce177927fc608464290cc2f8973d62e29af9f5e143be0a9"

      define_method(:install) do
        bin.install "sekiad"
        bin.install "sekiactl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia_0.2.0_darwin_arm64.tar.gz"
      sha256 "843be855bbf6d25318fbd4221a41afcdfb1ed3af99d4c6a3bfd9ebf3b25020ae"

      define_method(:install) do
        bin.install "sekiad"
        bin.install "sekiactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia_0.2.0_linux_amd64.tar.gz"
      sha256 "3b8ba29f3b4d49a70a01192251d0559dda059e842932946df657766f165ca328"
      define_method(:install) do
        bin.install "sekiad"
        bin.install "sekiactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia_0.2.0_linux_arm64.tar.gz"
      sha256 "e25d19f5922d8cd82b0985ec945cf30d49c8772f2920ac1b22284597f8c13baa"
      define_method(:install) do
        bin.install "sekiad"
        bin.install "sekiactl"
      end
    end
  end

  service do
    run [opt_bin/"sekiad"]
    keep_alive true
    log_path var/"log/sekiad.log"
    error_log_path var/"log/sekiad.log"
  end

  test do
    system bin/"sekiad", "--help"
    system bin/"sekiactl", "--help"
  end
end
