# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaGoogle < Formula
  desc "sekia Google agent - Gmail and Calendar bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.2.0"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia-google_0.2.0_darwin_amd64.tar.gz"
      sha256 "bd697e5ed47038b6f84bc64e7b2e94c7adbe9cb63a05a65c8c494a8ef763ab90"

      define_method(:install) do
        bin.install "sekia-google"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia-google_0.2.0_darwin_arm64.tar.gz"
      sha256 "ff7e87eed113b0d9a900ab36c502a0e607fd630a19a821afcbeccd31d065dd84"

      define_method(:install) do
        bin.install "sekia-google"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia-google_0.2.0_linux_amd64.tar.gz"
      sha256 "1b7e091e80b73621c2354b5bf5ccc730ad21e88363d1f4f11a123ae3dd48295c"
      define_method(:install) do
        bin.install "sekia-google"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.0/sekia-google_0.2.0_linux_arm64.tar.gz"
      sha256 "81fe3801f3624ad6226277fc11fe39cd63c2b23811ddedf94ffb1186c675ca4b"
      define_method(:install) do
        bin.install "sekia-google"
      end
    end
  end

  service do
    run [opt_bin/"sekia-google"]
    keep_alive true
    log_path var/"log/sekia-google.log"
    error_log_path var/"log/sekia-google.log"
  end

  test do
    system bin/"sekia-google", "--help"
  end
end
