# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaLinear < Formula
  desc "sekia Linear agent - GraphQL polling bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.1.4"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.4/sekia-linear_0.1.4_darwin_amd64.tar.gz"
      sha256 "92d2d260b668f827ab12237c304a95a32a003ad4490b2d4452234c2e71c9b1ec"

      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.4/sekia-linear_0.1.4_darwin_arm64.tar.gz"
      sha256 "1c4fe7c53fa01142abd50badbe951bcde40d24b77667f8f8f230b4fb96572c04"

      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.4/sekia-linear_0.1.4_linux_amd64.tar.gz"
      sha256 "7f14b008020a0dd8ebe08d80c3c63a8439e0a1e8cfa17d349446dcffb0129a7a"
      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.1.4/sekia-linear_0.1.4_linux_arm64.tar.gz"
      sha256 "8f92ee72b137fd5e479160c27841036e1bbcc2add63d93688e248df40fe1b473"
      define_method(:install) do
        bin.install "sekia-linear"
      end
    end
  end

  service do
    run [opt_bin/"sekia-linear"]
    keep_alive true
    log_path var/"log/sekia-linear.log"
    error_log_path var/"log/sekia-linear.log"
  end

  test do
    system bin/"sekia-linear", "--help"
  end
end
