# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SekiaSlack < Formula
  desc "sekia Slack agent - Socket Mode bridge"
  homepage "https://github.com/sekia-ai/sekia"
  version "0.2.1"
  license "Apache-2.0"

  depends_on "sekia-ai/tap/sekia"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.1/sekia-slack_0.2.1_darwin_amd64.tar.gz"
      sha256 "26eae1175370ea7cbbb090dd19f941ed8e1e4f095db0cb2945147137cca83f48"

      define_method(:install) do
        bin.install "sekia-slack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.1/sekia-slack_0.2.1_darwin_arm64.tar.gz"
      sha256 "33a9839ce307d0a874aeb0263e819eec37e0ee25442bea36803b79fd0bab33b2"

      define_method(:install) do
        bin.install "sekia-slack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.1/sekia-slack_0.2.1_linux_amd64.tar.gz"
      sha256 "bd4709f3c269e2bbfa58044975ad0d69fb0e24abdcc232d43e63122ea55c08f5"
      define_method(:install) do
        bin.install "sekia-slack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sekia-ai/sekia/releases/download/v0.2.1/sekia-slack_0.2.1_linux_arm64.tar.gz"
      sha256 "cb9d18f5c3b0d68b23279bfe2277991109d93add850748be36d1e637a6111688"
      define_method(:install) do
        bin.install "sekia-slack"
      end
    end
  end

  service do
    run [opt_bin/"sekia-slack"]
    keep_alive true
    log_path var/"log/sekia-slack.log"
    error_log_path var/"log/sekia-slack.log"
  end

  test do
    system bin/"sekia-slack", "--help"
  end
end
